version: "3.1"

services:
  bagisto-php-apache:
    build:
      args:
        uid: 1000
        user: $USER
        container_project_path: /var/www/html/
      context: .
      dockerfile: ./Dockerfile
    image: bagisto-php-apache
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./:/var/www/html/

  bagisto-php-queue:
    entrypoint: php artisan queue:work --tries=3 --timeout=60
    restart: unless-stopped
    image: bagisto-php-apache
    volumes:
      - ./:/var/www/html/

  bagisto-mysql:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_HOST: "%"
      MYSQL_ROOT_PASSWORD: root
    ports:
      - 3307:3306
    volumes:
      - ./.configs/mysql-data:/var/lib/mysql/
